env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - eslint:recommended
  - plugin:n/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:cypress/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - import
rules: {
  quotes: [error, single],
  indent: [error, 2],
  semi: [error, always],
  "@typescript-eslint/semi": [error, always],
  "template-curly-spacing": "off",
  "react/react-in-jsx-scope": "off",
  "react/jsx-filename-extension": [1, { "extensions": [".ts", ".tsx"] }],
  "@typescript-eslint/explicit-function-return-type": "off",
  "@typescript-eslint/space-before-function-paren": "off",
  "@typescript-eslint/no-floating-promises": "off",
  "no-extra-boolean-cast": "off",
  "n/no-missing-import": "off",
  "n/no-unsupported-features/es-syntax": "off",
  "import/no-unresolved": "off",
  "n/no-extraneous-import": "off",
  "@typescript-eslint/triple-slash-reference": "off",
  "n/no-unpublished-import": "off",
  complexity: [error, 4],
}
